version: '3.8'

services:
  thinkai-db:
    image: mysql:8.0
    container_name: thinkai-mysql
    restart: always
    environment:
      MYSQL_DATABASE: thinkai_db      # Tên DB dự án
      MYSQL_ROOT_PASSWORD: root       # Pass root (chỉ dùng cho Local Dev)
      MYSQL_USER: dev_user            # User phụ (optional)
      MYSQL_PASSWORD: thinkai123
    ports:
      - "3306:3306"                   # Map port ra ngoài để Workbench/Java kết nối
    volumes:
      - mysql_data:/var/lib/mysql     # Quan trọng: Giữ dữ liệu không bị mất khi tắt Docker
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  thinkai-api:
    build: .
    container_name: thinkai-backend
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      thinkai-db:
        condition: service_healthy
    env_file: .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://thinkai-db:3306/thinkai_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

volumes:
  mysql_data: