apiVersion: apps/v1
kind: Deployment
metadata:
  name: thinkai-backend
  namespace: thinkai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thinkai-backend
  template:
    metadata:
      labels:
        app: thinkai-backend
    spec:
      containers:
      - name: backend
        image: minhtuyetvoi/thinkai-backend:latest
        ports:
        - containerPort: 8081