apiVersion: v1
kind: Service
metadata:
  name: thinkai-backend
  namespace: thinkai
spec:
  type: ClusterIP
  selector:
    app: thinkai-backend
  ports:
    - name: backend
      port: 80
      targetPort: 8081